### PR TITLE
Allow stdlib CSV options to be passed through

### PR DESCRIPTION
**Pull request by ibroadfo**

### CODE REVIEW

**Comment by danielfone** [comment]
@ibroadfo Thanks! I like this. Good thinking keeping the stdlib options in a self-contained key. If you've got some time to fix the rails test suite, please do so. I don't imagine it's too hard. Otherwise I'll fix that up and merge as soon as I get a chance.

**Comment by ibroadfo** [comment]
So the build is passing, but not sure whether we want the rails 4.2 changes
to happen on this PR?

**Comment by danielfone** [comment]
Yeah, lgtm. I'll push a new version of the gem.

**Comment by ibroadfo** [comment]
:sunglasses:

**Pull request merged**
